@if($errors->any())

  @if( $errors->first('alert-success') || $errors->first('alert-danger') )
    <!-- if errors are defined at controller actions -->
    @foreach (['danger', 'success'] as $msg)
      @if($errors->has('alert-' . $msg))
      <div class="alert alert-{{ $msg }} alert-dismissible dismiss">
        <p class="m-b-0">{{ $errors->first('alert-' . $msg) }}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
      </div>
      @endif
    @endforeach

  @else
  <!-- if errors are auto generated by Validation Class -->
  <div class="alert alert-danger alert-dismissible dismiss" role="alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    @foreach($errors->all() as $error)
    <p class="mb-2"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>&nbsp;{{ $error }}</p>
    @endforeach
  </div>

  @endif

@endif

<!-- for validation erros using ajax   -->
<div class="alert alert-danger alert-dismissible p-3" role="alert" id="main-error-div" style="display: none">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <div id="list-ajax-error">

  </div>
</div>